# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailhole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='default_readers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
