# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0002_peer_default_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='slug',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
