# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import mailhole.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0004_populate_peer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_text_bytes',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='headers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_file',
            field=models.FileField(null=True, upload_to=mailhole.models.message_upload_to),
        ),
    ]
