# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import mailhole.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0008_message_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='headers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_file',
            field=models.FileField(upload_to=mailhole.models.message_upload_to),
        ),
    ]
