# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0009_message_fields_non_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('kind', models.CharField(choices=[('subject_match', 'Subject regex search'), ('sender_match', 'Sender regex search'), ('header_match', 'Header regex match')], max_length=30)),
                ('pattern', models.CharField(max_length=200)),
                ('examples', models.TextField(help_text='Eksempel-matches, én per linje. Linjer der starter med udråbstegn (!) er negative eksempler. Kommentarer starter med hegn (#).')),
                ('action', models.CharField(choices=[('spam', 'Markér som spam'), ('forward', 'Videresend')], max_length=30)),
                ('peer', models.ForeignKey(blank=True, help_text='Blank betyder "alle servere"', null=True, on_delete=django.db.models.deletion.CASCADE, to='mailhole.Peer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
