# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0010_add_filterrule'),
    ]

    operations = [
        # This migration only adds blank=True to the field,
        # and sqlmigrate correctly shows no SQL for this migration.
        # However, without SeparateDatabaseAndState, MySQL throws
        # a reference integrity error on this supposedly no-op migration.
        # Using SeparateDatabaseAndState avoids the integrity error.
        migrations.SeparateDatabaseAndState(
            [],
            [
                migrations.AlterField(
                    model_name='sentmessage',
                    name='created_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
