# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0011_created_by_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filtered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailhole.FilterRule'),
        ),
    ]
