# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import mailhole.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0013_add_filterrule_created_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='rcpt_to',
            new_name='rcpt_tos',
        ),
        migrations.AlterField(
            model_name='message',
            name='rcpt_tos',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='message',
            name='orig_mail_from',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='orig_message_file',
            field=models.FileField(
                null=True, upload_to=mailhole.models.orig_message_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='orig_rcpt_to',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
