# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0016_site_mailbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='email',
        ),
    ]
