# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0018_monitormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='default_action',
            field=models.CharField(choices=[('hold', 'Tilbagehold'), ('forward', 'Videresend')], default='hold', max_length=10),
        ),
    ]
