# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0020_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='outgoing_headers',
            field=models.TextField(default='', help_text='From message_file'),
            preserve_default=False,
        ),
    ]
