# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-21 17:37
from __future__ import unicode_literals

from django.db import migrations


def populate_message_outgoing_headers(apps, schema_editor):
    MessageModel = apps.get_model("mailhole", "Message")

    from mailhole.models import Message

    for o in MessageModel.objects.filter(outgoing_headers=""):
        Message._extract_outgoing_headers(o)
        o.save(update_fields=("outgoing_headers",))


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0021_message_outgoing_headers'),
    ]

    operations = [
        migrations.RunPython(populate_message_outgoing_headers),
    ]
