# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhole', '0022_populate_message_outgoing_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='data_retention',
            field=models.CharField(choices=[('keep', 'Behold'), ('delete', 'Slet')], max_length=10, null=True),
        ),
    ]
